spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        missing-queues-fatal: false

server:
  port: ${SERVER_PORT:8085}

app:
  kafka:
    user-topic: ${APP_KAFKA_USER_TOPIC:user.events}
    auth-topic: ${APP_KAFKA_AUTH_TOPIC:auth.events}
  rabbitmq:
    file-activity-exchange: ${APP_RABBITMQ_FILE_ACTIVITY_EXCHANGE:file.activity.exchange}
    file-activity-queue: ${APP_RABBITMQ_FILE_ACTIVITY_QUEUE:file.activity.notification.queue}
    file-activity-routing-key: ${APP_RABBITMQ_FILE_ACTIVITY_ROUTING_KEY:file.activity.notification}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
